name: Release

on:
  push:
    - master
  # release:
  #   types: 
  #     - created

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-
      - uses: secrethub/actions/env-export@v0.1.0
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          ORG_GRADLE_PROJECT_ossReleaseRepositoryUserName: secrethub://sshoogr/sshoogr/ossReleaseRepositoryUserName
          ORG_GRADLE_PROJECT_ossReleaseRepositoryPassword: secrethub://sshoogr/sshoogr/ossReleaseRepositoryPassword
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: release
